### ISSUE TITLE
Error when plotting phase folded RVs

### ISSUE THREAD

**Issue by jvines** [nespinoza/juliet#1]
Hi,

I got the following error when Juliet was going through the plot of phase folded RVs!

/Users/jvines/anaconda2/lib/python2.7/site-packages/numpy/core/fromnumeric.py:2920: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
/Users/jvines/anaconda2/lib/python2.7/site-packages/numpy/core/_methods.py:85: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
Traceback (most recent call last):
  File "juliet.py", line 1807, in <module>
    ax_res.set_ylim([-5*np.median(rv_bin_err),5*np.median(rv_bin_err)])
  File "/Users/jvines/anaconda2/lib/python2.7/site-packages/matplotlib/axes/_base.py", line 3457, in set_ylim
    bottom = self._validate_converted_limits(bottom, self.convert_yunits)
  File "/Users/jvines/anaconda2/lib/python2.7/site-packages/matplotlib/axes/_base.py", line 3068, in _validate_converted_limits
    raise ValueError("Axis limits cannot be NaN or Inf")
ValueError: Axis limits cannot be NaN or Inf

**Comment by nespinoza** [comment]
Hi @jvines! Thanks for catching this --- this was just a plotting bug, which has now been resolved in [commit 6ebb2df4d5bdea87ad22d238a73f51f01c1e4454](https://github.com/nespinoza/juliet/commit/6ebb2df4d5bdea87ad22d238a73f51f01c1e4454). I will thus proceed to close this issue as resolved!

Thanks for using `juliet`!
