### ISSUE TITLE
Suggestion - allow file saving with get_all_TESS_data

### ISSUE THREAD

**Issue by melissa-hobson** [nespinoza/juliet#103]
I'm using the get_all_TESS_data function to get TESS data from MAST - it's a very convenient function, but it would be even better if there was the option to save the data so it doesn't have to download them from MAST each time. Would it be possible to add an option for this?

**Comment by nespinoza** [comment]
Hi @melissa-hobson,

 This sounds like a handy petition indeed! I doubt this will reach the point of implementation (given the long list of things "to do") but if you find the time to implement it directly in the `get_all_TESS_data` function --- please feel free to submit a PR!

N.
