### ISSUE TITLE
GP-only fit on photometry not working

### ISSUE THREAD

**Issue by melissa-hobson** [nespinoza/juliet#104]
I'm trying to fit a GP (only) on photometric data, as done in the docs, and it crashes with the following error:

![imagen](https://github.com/nespinoza/juliet/assets/34136975/442e16e7-97db-4659-9348-5fda1cc3bb20)
![imagen](https://github.com/nespinoza/juliet/assets/34136975/de92acf3-8822-4406-bfbb-3858a03067bc)

Any idea why? I know this used to work, I can fit GP+transit simultaneously, and GP-only fits on RV data - it's just the GP-only on photometric data that's failing.

**Comment by nespinoza** [comment]
Hi @melissa-hobson,

 Can you please provide a minimum working example that reproduces the error (perhaps internally)? That could help me pinpoint the source. From the looks of it, it seems as if the `sigma_w_TESS` was missing --- but it could also be an issue I introduced with the latest `juliet` updates.

N.

**Comment by nespinoza** [comment]
Thanks for that @melissa-hobson! I found the bug and this should work on the latest version I just released, `v.2.2.4` --- can you do `pip install juliet --upgrade` and check this is the case?

Thanks!

N.

**Comment by melissa-hobson** [comment]
Yes, that works! Thank you :)

**Comment by nespinoza** [comment]
Solved in v.2.2.4
