### ISSUE TITLE
 AttributeError: type object 'NestedSampler' has no attribute '__code__'

### ISSUE THREAD

**Issue by mdredyanahmed** [nespinoza/juliet#107]
<img width="936" alt="Screenshot 2023-12-13 at 7 41 06 PM" src="https://github.com/nespinoza/juliet/assets/67976050/8a6fb0ff-a285-4f73-859e-07268cbf40bd">

can someone help to resolve this problem?
i have latest version of juliet

**Comment by nespinoza** [comment]
Closing as this was fixed in `2.2.7`.
