### ISSUE TITLE
Can no longer pass keyword arguments to dynesty

### ISSUE THREAD

**Issue by radicamc** [nespinoza/juliet#109]
As the title says, keyword arguments are no longer able to be passed to dynesty via juliet.fit (not sure about other samplers).
I believe this is because line 1683 ```args = vars(sampler).keys()``` is not actually returning a list of possible dynesty arguments, resulting in everything failing the cross-check with the passed keywords.

**Comment by nespinoza** [comment]
Fixed on latest version (2.2.6).

N.
