### ISSUE TITLE
posteriors.dat not showing instrument parameters

### ISSUE THREAD

**Issue by jvines** [nespinoza/juliet#11]
Exactly what the title says... My posteriors for a run with 3 different photometry instruments didn't show any of the instrumental parameters.

**Comment by nespinoza** [comment]
Hi Jose,

 As you might have guessed, it is practically impossible for us to debug this if you don't provide us with some information such as your prior file, or lightcurves and any terminal text you encountered.

 If you can't share any of this, creating a mock dataset that reproduced the error would be good. You can also contact us directly to share these. Also: are you using the classic juliet or the pip installable version?

 Thanks

N.

PS: This also applies to your other issue.

**Comment by jvines** [comment]
Oops, you are right. Silly me...
I am using the pip installable version (but installed through the cloned repo)

The priorfile I used is:

```
# Physical parameters of the transiting system:
P_p1                  Normal            0.35602,0.1
t0_p1                 Normal            2457394.06085,0.01
a_p1                  Uniform           0.001,30.0
r1_p1                 Uniform           0.0,1.0
r2_p1                 Uniform           0.0,1.0
ecc_p1                FIXED             0.0
omega_p1              FIXED             90.0
# Photometric priors for NGTS photometry:
q1_NGTS                 Uniform           0.0,1.0
q2_NGTS                 Uniform           0.0,1.0
mdilution_NGTS          FIXED             1.0
sigma_w_NGTS            Jeffreys          1.,1000
mflux_NGTS              Normal            0.0,0.1
# Photometric priors for EULERV photometry:
q1_EULERV                 Uniform           0.0,1.0
q2_EULERV                 Uniform           0.0,1.0
mdilution_EULERV          FIXED             1.0
sigma_w_EULERV            Jeffreys          1.,1000
mflux_EULERV              Normal            0.0,0.1
# Photometric priors for SAAOV photometry:
q1_SAAOV                 Uniform           0.0,1.0
q2_SAAOV                 Uniform           0.0,1.0
mdilution_SAAOV          FIXED             1.0
sigma_w_SAAOV            Jeffreys          1.,1000
mflux_SAAOV              Normal            0.0,0.1
```

And the posteriors.dat file I get is
```
# Parameter Name     	 	 Median       	 	 Upper 68 CI  	 	 Lower 68 CI 
P_p1               	 	 0.3560751172 	 	 0.0000000003 	 	 0.0000000003
t0_p1              	 	 2457394.0459365151 	 	 0.0016037486 	 	 0.0016966965
a_p1               	 	 1.4026235387 	 	 0.0301359152 	 	 0.0284730133
r1_p1              	 	 0.9921177757 	 	 0.0052643905 	 	 0.0087762751
r2_p1              	 	 0.1396865428 	 	 0.0058853157 	 	 0.0086201927
p_p1               	 	 0.1396865428 	 	 0.0058853157 	 	 0.0086201927
b_p1               	 	 0.9881766636 	 	 0.0078965857 	 	 0.0131644127
```

I do not know if I can share the dataset, so I'll try to create a mock dataset that reproduces the error...

Also, the call to Juliet was:

```
python juliet.py -lcfile star/LCs/full.dat -priorfile star/Priors/Priors_NGTS.dat -instrument_supersamp NGTS -n_supersamp 30 -exptime_supersamp 0.0208 -pl 0. -pu 1. -ofolder star/full/ -nlive 500 --use_dynesty --dynamic -dynesty_bound multi -dynesty_nthreads 4
```

There were no warnings or errors at the end of the fitting procedure.

I'll update with information about the dataset used.

**Comment by nespinoza** [comment]
Hi Jose,

 Great, thanks for the input! One detail is that as it is explained in the readthedocs page (https://juliet.readthedocs.io/en/latest/user/quicktest.html), calling the code using the ``juliet.py`` extension is going to lose support soon. Currently the importable version of the code is working perfectly (again, check the tutorials!), and I'm working on making it terminal callable (i.e., ``juliet -lcfile etcetc`` --- the code is ready to do this, I just have to find some time to do this soon). So right now you because you are using the ``juliet.py`` call, you are not using the latest version (but it shouldn't be an issue for your fit!).

 In any case, please submit the case and I'll take a look at it.

 Best,

N.

**Comment by jvines** [comment]
I re-ran the fit... and for some reason it worked this time. I have no idea why because it was the same call and everything (just changing the output folder)

I guess this can be closed now..

**Comment by nespinoza** [comment]
OK! Feel free to re-open if something like this happens.
