### ISSUE TITLE
TTV fit wil fail for more than one transiting planet with T parametrization

### ISSUE THREAD

**Issue by melissa-hobson** [nespinoza/juliet#110]
Related to [Issue 97](https://github.com/nespinoza/juliet/issues/97) (and Manu Stalport's fix also fixes this), but broader, this applies to any TTV fit with two or more transiting planets because of how the lightcurve dictionary is built. The current code (starting from line 618 of fit.py) has the following:

```
        if dictype == 'lc':
            for i in range(ninstruments):
                dictionary[inames[i]]['TTVs'] = {}
                for pi in numbering_planets:
                    dictionary[inames[i]]['TTVs'][pi] = {}
                    dictionary[inames[i]]['TTVs'][pi]['status'] = False
                    dictionary[inames[i]]['TTVs'][pi]['parametrization'] = 'dt'
                    dictionary[inames[i]]['TTVs'][pi]['transit_number'] = []
                for pri in self.priors.keys():
[...]
                    if pri[0:2] == 'dt' or pri[0:2] == 'T_':
                      
                        if pri[0:2] == 'T_':
                            dictionary[
                                inames[i]]['TTVs'][pi]['parametrization'] = 'T'
                        planet_number, instrument, ntransit = pri.split('_')[1:]
                        if inames[i] == instrument:

                            dictionary[inames[i]]['TTVs'][int(
                                planet_number[1:])]['status'] = True
                            dictionary[inames[i]]['TTVs'][int(
                                planet_number[1:])]['transit_number'].append(
                                    int(ntransit))

```
As the line storing the parametrization is not in a loop on `pi` and there has already been such a loop, it will only alter it for the last planet - all the others will remain with parametrization = dt as initialized. 

To fix this while also making it more similar to how the rest of the TTV dictionary is written, I suggest moving that key writing down with the others, like so:

```
                    if pri[0:2] == 'dt' or pri[0:2] == 'T_':
                
                        planet_number, instrument, ntransit = pri.split('_')[1:]

                        if inames[i] == instrument:
                            if pri[0:2] == 'T_':
                                dictionary[inames[i]]['TTVs'][int(
                                    planet_number[1:])]['parametrization'] = 'T'

                            dictionary[inames[i]]['TTVs'][int(
                                planet_number[1:])]['status'] = True
                            dictionary[inames[i]]['TTVs'][int(
                                planet_number[1:])]['transit_number'].append(
                                    int(ntransit))
```

which has the advantage of using the same method to get the planet number key for all the TTV keys, and appears to work correctly (my fit now runs, at least!).

**Comment by nespinoza** [comment]
Thanks Melissa! If your fit works as expected, and a single-ttv fit works as well, please consider making a Pull Request of this fix!

**Comment by LucaNap** [comment]
Dear @melissa-hobson , @nespinoza , I think there's another line that needs changing. In my case, I have two planets -- the first of  which has TTVs and the second one only a monotransit. Of course I want to fit the TTVs of the first planet only. However, at line 3188 of the latest fit.py:

```
            for i in self.numbering:

                if self.Tparametrization[i]:

                    all_Ts[i], all_ns[i] = np.array([]), np.array([])
```

I get an error because self.Tparametrization is a dictionary with only "1" in it, so when i=2 I get a "KeyError: 2". I simply changed it so that:

```
            for i in self.numbering:

                if i in self.Tparametrization:

                    all_Ts[i], all_ns[i] = np.array([]), np.array([])
```

And now apparently it works.
