### ISSUE TITLE
results.lc.evaluate not working when given a custom time array

### ISSUE THREAD

**Issue by jvines** [nespinoza/juliet#13]
Hi,

I'm running Juliet on a single night photometry observation and after running juliet, since we only have one night worth of data, the lightcurve isn't sufficiently sampled, so I tried running 
```
t = sp.linspace(dataset.t_lc[0]. dataset.t_lc[-1], 10000)
transit_model = results.lc.evaluate(INST, t=t)
```

but it throws the following error (rather randomly because sometimes it works..?)

```
-------------------------------------
ValueErrorTraceback (most recent call last)
<ipython-input-34-58d2cdf36611> in <module>
      6 t = sp.linspace(dataset.t_lc[0], dataset.t_lc[-1], 10000)
----> 7 transit_model = results.lc.evaluate(INST, t=t)
      8 
      9 # Extract period and time-of-transit center for the planet:

/anaconda3/lib/python3.7/site-packages/juliet-2.0.17-py3.7.egg/juliet/fit.py in evaluate_model(self, instrument, parameter_values, resampling, nresampling, etresampling, all_samples, nsamples, return_samples, t, GPregressors, LMregressors, return_err, alpha, return_components)
   1874                                               nresampling = nresampling, etresampling = etresampling, all_samples = all_samples, \
   1875                                               nsamples = nsamples, return_samples = return_samples, t = t, GPregressors = GPregressors, \
-> 1876                                               LMregressors = LMregressors, return_err = return_err, return_components = return_components)
   1877             if return_samples:
   1878                 if return_err:

/anaconda3/lib/python3.7/site-packages/juliet-2.0.17-py3.7.egg/juliet/fit.py in evaluate_model(self, instrument, parameter_values, resampling, nresampling, etresampling, all_samples, nsamples, return_samples, t, GPregressors, LMregressors, return_err, alpha, return_components)
   1616                         self.variances = self.model['global_variances']
   1617                     else:
-> 1618                         self.residuals = self.data[instrument] - self.model[instrument]['deterministic']
   1619 
   1620                     # If extrapolating (t is not None), evaluate the extrapolated model with a lightcurve/rv model

ValueError: operands could not be broadcast together with shapes (2847,) (10000,) 
```
To my understanding this should work (and it does... randomly), what could be happening?? If you need any more info please let me know

Cheers.

**Comment by nespinoza** [comment]
Hi Jose,

 Thanks! Can you generate a reproducible example?

N

**Comment by jvines** [comment]
I haven't been able to reproduce it, but I found that during the generation of the model `self.modelOK` is set as False when it crashes and this happens because of the inc_inv_factor > 1 -- which makes the randomness of the error make sense.

Might I suggest checking for model validity while going through the sample indexes in the evaluate_model function?

Maybe an evaluation if the samples are valid and if a good enough number of samples are valid, just drop the invalid ones?

**Comment by jvines** [comment]
I think it's worth noting I fixed the eccentricity and omega to 0 and 90 respectively and I'm fitting directly for b and p, as using r1 and r2 is producing b > 1 which is incorrect for this particular system... I'm also fitting photometry only, no RVs involved

**Comment by nespinoza** [comment]
Hey @jvines --- we made some changes in the current repo that should have solved this. Could you check? If you don't remember, I'll just go ahead and close this issue but if you see it again, feel free to open a new one. Either way, I'll wait for your feedback.

N.
