### ISSUE TITLE
issue with running with multi-dimensional squared exponential kernel

### ISSUE THREAD

**Issue by JamesKirk11** [nespinoza/juliet#14]
I am running into an issue running multi-dimensional Sq Exp kernels. I can reproduce the online tutorials and fit my own data with both a linear model and a transit-only model. However, when I switch on the GP fitting, I get a bunch of errors from dataset.fit() culminating in:

ValueError: could not convert string to float: '0.695242354918611711-309'

It is possible that this is a prior-related issue. I am attaching the priors file here (as a .txt file) and a plot of the white light curve I'm trying to fit.

[wasp39_priors.txt](https://github.com/nespinoza/juliet/files/4377070/wasp39_priors.txt)

[white_light_curve.pdf](https://github.com/nespinoza/juliet/files/4377067/white_light_curve.pdf)

Thanks!

**Comment by dianadianadiana** [comment]
Hi James,

This is not an unheard error! I've run into this myself a few times as 
well and it's just been a user-input mistake.
Would you mind sharing the data you have so we can better fix it and try 
running it on our own?
Also since you are using the GP, all the extra fitting data would be 
great too.

Thanks and stay healthy,
Diana

**Comment by JamesKirk11** [comment]
Hi Diana,

Thanks for your quick response. Yes it's not unlikely that I'm causing this error!

The times, fluxes and errors are attached here. At the moment I am just running the GP with time as the input so this should be all you need.

Thanks, you too!

James

[data.txt](https://github.com/nespinoza/juliet/files/4381236/data.txt)

**Comment by dianadianadiana** [comment]
Hi James,

I tried sending this email but it bounced back twice but maybe it went 
through, sorry if you got it 3 times! --

I actually had no problems! I used the same priors you had, but maybe I 
have a different set up in the code?
I attached a zip file where I did three fits and here are their lnZs:
(1) transit only 979.751
(2) transit + LT 1005.857
(3) transit + GP 1041.549
So including the GP gives us the winning model.

I included the code I used to produce the plots and whatnot if you want 
to try -- depending on the model, comment in/out GP_regressors_lc, 
lcfilename; as well as the prior parameters.

Let me know if this ends up working on your computer!

Best,
Diana

**Comment by JamesKirk11** [comment]
Hi Diana,

Thanks a lot for this and sorry about the email issue, I think it might have been going to an old institutional email associated with my GitHub! Please could you resend the zip file to james.kirk@cfa.harvard.edu?

Cheers,
James

**Comment by nespinoza** [comment]
This seems to have been an internal script problem, so I'm closing it. @JamesKirk11 feel free to open another issue if this was not the case! (thanks @dianadianadiana for double checking this!)

N.
