### ISSUE TITLE
Joint Fit Example: "Parameters Converging to Edge of Prior"? 

### ISSUE THREAD

**Issue by nascarsdale** [nespinoza/juliet#15]
Hi Nestor and co., 

Thanks for this great tool! I have juliet installed (along with multinest and its LAPACK dependency) and am running through the tutorials in preparation for performing my own fits. However, in running the joint fit example of the TOI 141 system myself, multinest warns me "Parameter           [n]  of mode            1  is converging towards the edge of the prior", where n has been 14, 21, or 4 (or some permutation of two of those). 

Possibly relatedly, I am also finding that this fit runs for several hours without completion. I am using a reasonably high-end laptop computer which was able to complete the light curve-only and RV-only fits in a minute or so, so this surprised me. I was wondering if this was an issue known to you? The "convergence towards the edge of the prior" warning made me think it might be an issue related to my multinest install and not just laptop performance issues. 

Thank you, and I hope you and yours are safe and healthy in these times of global illness. 

-Nicholas

**Comment by nespinoza** [comment]
Hi @nascarsdale --- this might be related to issue https://github.com/nespinoza/juliet/issues/23. Please follow the discussion over there; sorry for coming so late to this.

Néstor

**Comment by nespinoza** [comment]
Hey @nascarsdale --- this has been solved in https://github.com/nespinoza/juliet/issues/23! I'll go ahead and close this issue.

N.

**Comment by nascarsdale** [comment]
Hi @nespinoza - thank you so much! 

I've recently been revisiting juliet for joint fitting purposes, and I'm bizarrely finding that this problem has persisted (apologies that I'm just replying to your months-ago fix!) I examined #23 and made the same changes made in the documentation (turning the TESS JD in the prior and data to BJD), and also used np.random.seed (22) as was done in that thread just to be safe. Running the example code, I'm still being told repeatedly that "MultiNest Warning!  Parameter            4  of mode            1  is converging towards the edge of the prior" (this is occasionally repeated with Parameters 14 and 21, as well). This remains true after a few hours of runtime over several attempts. 

My computer handles the other examples in the tutorials without any trouble (<1 minute runtime for each), so I don't believe it's a processing time issue. I am currently using multinest v3.10 and pymultinest v2.10 (although the problem also existed for v2.9, since I updated it recently). Aside from the addition of np.random.seed(22), my code is copied and pasted from the tutorials. 

I am somewhat baffled as to what's going on here. I didn't want to mindlessly dump the output files from the "out_folder" but if those might be useful, I'd be happy to attach them. 

Thank you in advance for any light you might be able to shed on this strange problem!

**Comment by nespinoza** [comment]
Hey @nascarsdale --- yes, that might be useful! Send it via email at nespinoza at stsci.edu. I'll reopen this issue until we find the root of this problem :-).

N.

**Comment by nascarsdale** [comment]
Sent! Thank you so much!

**Comment by nespinoza** [comment]
Hi @nascarsdale,

 I recently ran this and all looks good now (at least in the docs). I'll close this issue for now, but if you keep finding this error, please open it up again or make a new issue!

 Thanks for bringing this up.

Néstor
