### ISSUE TITLE
Problem when instrument names have underscores?

### ISSUE THREAD

**Issue by jvines** [nespinoza/juliet#2]
Hi,

I was running Juliet for a joint photometry-rv analysis and the program began spanning the following error message to my terminal:

For context, I have data from SAAO in the V and I band, so I thought of an underscore to separate them in the phot file and the prior file, and the error only appeared when fitting for r_1 and r_2 with the --efficient_bp -pl 0. -pu 1. flag.

Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 315, in 'calling callback function'
  File "/Users/jvines/anaconda2/lib/python2.7/site-packages/pymultinest/run.py", line 212, in loglike
    return LogLikelihood(cube, ndim, nparams)
  File "juliet.py", line 959, in loglike
    coeff1, coeff2 = reverse_ld_coeffs(lc_dictionary[instrument]['ldlaw'], priors['q1_' + ld_iname[instrument]]['cvalue'],
KeyError: 'SAAO_V'

The issue was fixed when I removed the underscore.

**Comment by nespinoza** [comment]
Hi @jvines! This is indeed expected; instrument names should not have underscores. We will put this in the documentation!

**Comment by mrdmetal** [comment]
And also juliet won't run if the instrument name has numbers, like when you are using pre and post-fix data from the same instrument: PFS1, PFS2, HARPS1, HARPS2, and so on.
I changed it to PFSold, PFSnew and it runs without issues.
