### ISSUE TITLE
AttributeError: dlsym(RTLD_DEFAULT, run): symbol not found

### ISSUE THREAD

**Issue by rrpastro** [nespinoza/juliet#28]
I was trying to run the tutorial after installing the required packages but came across this error message:
--
AttributeError: dlsym(RTLD_DEFAULT, run): symbol not found
--
 while I tried to fit the data in this step:

results =  dataset.fit()

I did not see the solution specific to this problem. I guess it is related with some dependencies but could not figure out what might have caused it. Would you please help me to fix this issue. Thanks!

**Comment by nespinoza** [comment]
Hi @rrpastro --- this seems like it is a `MultiNest` issue. One quick way to check this is to open a python script/terminal/jupyter notebook and do `import pymultinest` --- my bet is that you'll get this error there as well.

Have you followed the installation instructions for `pymultinest` in the Read the Docs (https://juliet.readthedocs.io/en/latest/user/installation.html) (including the `export LD...` step)? If you are having troubles installing MultiNest, you can always try `dynesty` instead (`results = dataset.fit(use_dynesty=True)`).

Let me know if that works!

N.

**Comment by rrpastro** [comment]
Hi @nespinoza  -- thanks for your suggestion. I checked 'import pymultinest' and get no error message. Yes, I followed the installation instructions for 'pymultinest'. I reinstalled and checked, but still get the same error at same point. 

However, using 'dynesty' does not give that error. So, I will use 'dynesty' like you have suggested. 

Cheers,
R.

**Comment by nespinoza** [comment]
Hi @rrpastro --- did you do the `import pymultinest` followed by the `results = dataset.fit()` call and still got this error? I'm a bit puzzled this evident MultiNest error doesn't show up when you do `import pymultinest`. Are you sure you are not using an already opened notebook? Or another version of python?

**Comment by icweaver** [comment]
Hi all, I think I've run into this same problem before. @rrpastro, are you using the pypi version of `pymultinest` by any chance? I'm not sure if this is just a platform specific issue, but things seemed to work alright if I just used conda's version instead (`conda install pymultinest`)

**Comment by rrpastro** [comment]
Hi @nespinoza -- yes, I get the same error even after successfully being able to import `pymultinest`.  I am running it in Python 3.7.3 environment. I opened a fresh notebook today and checked today again. 

Hi @icweaver -- Thanks for your suggestion. I installed using pip and followed other steps as mentioned in the webpage. For some reason, I am unable to install using conda. I get 'PackagesNotFoundError'.

**Comment by icweaver** [comment]
Oh, apologies, I didn't relive that I had `conda-forge` as a default channel. You can either add it to your `.condarc` and re-try the command, or just do `conda install -c conda-forge pymultinest` to do an explicit install

**Comment by rrpastro** [comment]
Thanks @icweaver for the update. I did `conda install -c conda-forge pymultinest` and looks like it is working now.

**Comment by ameliahenkel** [comment]
Hello @icweaver @nespinoza @JohannesBuchner  -- I'm running into this same issue with PyMultiNest when I try to use `bilby.run_sampler()`.  I've already tried
-running `import pymultinest` in a test script; works fine
-reinstalling MultiNest according to the instructions linked above (am able to successfully do so)
-removing the build folder, then remaking it and re-doing `cmake ..` and `make` (those commands work)
-`conda install -c conda-forge pymultinest` did not work (after trying the above steps sequentially).  It provides the following error message, if this is useful:
```
Channels:
 - conda-forge
Platform: osx-arm64
Collecting package metadata (repodata.json): done
Solving environment: failed

LibMambaUnsatisfiableError: Encountered problems while solving:
  - nothing provides multinest needed by pymultinest-2.11-pyh707e725_4

Could not solve for environment specs
The following package could not be installed
└─ pymultinest =* * is not installable because it requires
   └─ multinest =* *, which does not exist (perhaps a missing channel).
```

I'm writing to politely enquire about advice on next steps?  So sorry for all the messages lately @JohannesBuchner ! I've used PyMultiNest for the past couple of years, and for some reason, now my computer wants nothing to do with it!

**Comment by JohannesBuchner** [comment]
Try creating a fresh conda environment.

**Comment by ameliahenkel** [comment]
Hi @JohannesBuchner -- I tried that and still receive the same error message somehow

**Comment by JohannesBuchner** [comment]
Yes, this was recently mentioned here: https://github.com/JohannesBuchner/PyMultiNest/issues/267#issuecomment-2856072844 .
Please open a PR if you have found a working solution that could help others.

**Comment by JohannesBuchner** [comment]
Regarding multinest not being on conda, the ingestor is at: https://github.com/conda-forge/multinest-feedstock/ so please open an issue there. It looks like the same cmake issue caused the upgrade to not succeed.

See this PR: https://github.com/conda-forge/multinest-feedstock/pull/14 
and then clicking to the CI logs gives: https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=1236967&view=logs&j=7b6f2c87-f3a7-5133-8d84-7c03a75d9dfc&t=9eb77fd2-8ddd-5444-8fc0-71cb28dcb736&l=989
