### ISSUE TITLE
`instrument` 's name bug

### ISSUE THREAD

**Issue by TakuNishiumi** [nespinoza/juliet#29]
Hello,

I probably found a bug, so I report here.
https://juliet.readthedocs.io/en/latest/user/priorsnparameters.html#exoplanets-with-juliet-pt-i-planetary-parameters
When I input the name of `instrument` in this link as M_1, it occured the error.
It seems `instrument` distinguish the intrument name by using "_", so the error might happened.
Could you check this?

Thank you.
Taku

**Comment by nespinoza** [comment]
Hi Taku,

 Indeed, the instrument names, in general, should not have underscores in the names (in your case, you might want to call the instrumnet `M-1` instead). I'll write a warning in the documentation to note this!

 Thanks!
Néstor

**Comment by TakuNishiumi** [comment]
Thank you for your quick response!
