### ISSUE TITLE
Document: n_live_points

### ISSUE THREAD

**Issue by TakuNishiumi** [nespinoza/juliet#38]
https://juliet.readthedocs.io/en/latest/user/api.html#juliet.fit

Hi, nespinoza,
I found that
class juliet.fit says n_live_points=1000 as default, but the below explanation says default is 500.
Which is True?

Sincerely,
TakuNishiumi

**Comment by nespinoza** [comment]
Hi @TakuNishiumi!

 Indeed, the docstring got it wrong --- it is 1000 indeed. Thanks for the catch --- will solve it ASAP!

N.

**Comment by nespinoza** [comment]
Fixed in the latest `juliet` version!
