### ISSUE TITLE
efficient_bp

### ISSUE THREAD

**Issue by DJArmstrong** [nespinoza/juliet#4]
Hi Nestor,

The python calls in tutorials 1 and 2 have the --efficient_bp argument but it looks like that has been commented out in juliet.py. It makes the tutorial calls error if copy pasted directly.

Cheers,
Dave

**Comment by nespinoza** [comment]
Hi @DJArmstrong --- thanks for this. I have removed the calls from the tutorials.

Best

Néstor

**Comment by nespinoza** [comment]
I have also removed the mention of this call in the rest of the wiki!

Thanks again,

Néstor
