### ISSUE TITLE
transit + RV+GP joint fit problems

### ISSUE THREAD

**Issue by TianjunGan** [nespinoza/juliet#46]
Hi Nestor, currently juliet can perform a joint fit for transit and RV data along with independent GP models. But it seems juliet can not link the two GP models (i.e., share the L and Prot parameter between the transit and RV GP models but use independent B and C for transit and RV)? Is it possible to implement this?

Thanks so much!
Tianjun

**Comment by nespinoza** [comment]
Hi @TianjunGan,

 This is currently allowed to be done in `juliet` (see https://juliet.readthedocs.io/en/latest/tutorials/gps.html).

N.
