### ISSUE TITLE
Tutorial 2 stuck

### ISSUE THREAD

**Issue by DJArmstrong** [nespinoza/juliet#5]
Hi Nestor,

Trying the second tutorial and the code gets stuck - the following message gets printed repeatedly and has been going for most of a day now. I'm just running the tutorial call with no changes.

Cheers,
Dave

Random walk proposals appear to be extremely inefficient. Adjusting the scale-factor accordingly.

**Comment by nespinoza** [comment]
Hi Dave,

 Do you have the dynesty version from pip install or did you clone the repo from the dynesty GitHub? If the former, that might be the problem. If not, could you try running the call again and see if the problem persists?

 Best

Néstor

**Comment by DJArmstrong** [comment]
Ah that was it. I had the pip version - reinstalling with the github version of dynesty fixed it (although still with a lot of the same line appearing).

Thanks!

**Comment by nespinoza** [comment]
Cool; glad that solved it! Closing this then.

N.
