### ISSUE TITLE
Evaluation of global LC model not working

### ISSUE THREAD

**Issue by JonasKemmer** [nespinoza/juliet#51]
Hey Nestor, 

I encountered some bug in the evaluation of global LC models that I am not able to resolve myself.

The setting is the following: 
I use only a global GP ("_lc") and different instrumental parameters (sigma_w, mflux, mdilution) for a set of photometry from different instruments to search for the rotation period in a light curve.
The fit seems to have worked (it converges and produces the pkl-file and posterior). However, I would like to plot the light curve and model. But this unfortunately doesn't work.

I use the results from the juliet.fit-object and try to run 
```python
  model_lc = results.lc.evaluate("instrument",  t=model_times,  GPregressors=model_times)
```
where `instrument` is one of the instruments that is used and `model_times` are the super-sampled model times. I usually used this for RV fits, but I assume it should work the same for light curves.

Unfortunately, it  produces the error (please ignore the lines given in the traceback, they refer to the pep-formated code):

```
Traceback (most recent call last):
  File ".../juliet/juliet/fit.py", line 2793, in evaluate_model
    x = self.evaluate_model(instrument = instrument, parameter_values = self.posteriors, resampling = resampling, \
  File ".../juliet/juliet/fit.py", line 2430, in evaluate_model
    ginstrument] = dummy_indexes
UnboundLocalError: local variable 'dummy_indexes' referenced before assignment
```

I was able to trace back the declaration of `dummy_indexes` to l. 1998 (last commit of yours). There the variable is assigned, but only within an else-statement that is valid for RV models. I assume that this may be an indentation error and therefore unindented the line once. 

However, this only brought up another error:

```
Traceback (most recent call last):
  File ".../juliet/juliet/fit.py", line 2793, in evaluate_model
    x = self.evaluate_model(instrument = instrument, parameter_values = self.posteriors, resampling = resampling, \
  File ".../juliet/juliet/fit.py", line 2433, in evaluate_model
    self.generate_lc_model(
  File ".../juliet/fit.py", line 3172, in generate_lc_model
    self.model['global'][self.instrument_indexes[
IndexError: index 854 is out of bounds for axis 0 with size 854
``` 
I tried to dig down deeper, but was not able to fully understand the differences that are necessary for the light curve models in comparison to the RV models.
For example, I could see that you set `self.model['global'] = np.ones(len(t))` for the RVs (l. 2123), while you don't do so for the lc models.
However, adding this lead only down to the "rollback" in l. 2207 and following, where even more variables were unassigned because they were only defined in some rv-else statements.

Do you have any idea what the issue could be?

**Comment by nespinoza** [comment]
Hi @JonasKemmer,

 Sorry for coming so late to this. I do have an idea on what is going on, but don't have the time today to work on this. Will leave it on my plate to fix --- will come back to this later in the week to fix!

Néstor

**Comment by nespinoza** [comment]
Tracking back to old bugs. @JonasKemmer --- is this still an issue or you solved it with your PR? A working example would be great to check.

N.
