### ISSUE TITLE
multi-dimensional GP_regressors

### ISSUE THREAD

**Issue by OliverQL** [nespinoza/juliet#52]
Hi everyone
Maybe I'm dumb but I just follow the online tutorial to learn and write my code.
I saw the GP_regressors_lc in the tutorials is  only the "times" of light curve.
I'm wondering if there is any way to make a multi-dimensional array for GP_regressors? 
For example, including "times", "airmass" and other addtional parameters?

Thanks.

**Comment by nespinoza** [comment]
Hi @OliverQL,

 Sorry for coming so late to this. You can actually do this! I have a notebook here that I intend to join to the documentation eventually in which I analyze a set of WASP-121b transits from HST and I do just this: https://github.com/nespinoza/w121-stis/blob/master/Analysis.ipynb --- jump to Section 3.2 to check the analysis out.

 Hope this helps!

 Best,
Néstor
