### ISSUE TITLE
NaN errors for the Bayesian evidence with dynesty

### ISSUE THREAD

**Issue by jordibp99** [nespinoza/juliet#60]
Hello. 

When trying to find the best-fitting model for radial velocity data I have issues with the error of the Bayesian evidence for some models in wide volume priors. If I fit a linear trend or a linear trend + 1 planet to the data, everything works correctly. But, when I add an additional planet the Bayesian evidence is calculated but the error is NaN. If I considerably shrink the volume prior, the problem dissapears.

I do not know if anyone has found the same problem and has any idea on the solution.

**Comment by nespinoza** [comment]
Hi @jordibp99,

 Thanks for bringing this up! Could you share a [minimum working examples](https://stackoverflow.com/help/minimal-reproducible-example) for this problem so I can take a look at it? Doesn't have to be your data, it can be a mock dataset.

 Thanks in advance!

Néstor

**Comment by jordibp99** [comment]
My code is almost identical to the juliet tutorials:
`directory="/home/jordi/Documents/github/"
priors_linear_2p = {}
# Name of the parameters to be fit:
params_linear_2p = ['P_p1','t0_p1','P_p2','t0_p2','mu_HARPS','mu_HPF',\
          'K_p1', 'ecc_p1', 'omega_p1','K_p2', 'ecc_p2', 'omega_p2','sigma_w_HARPS',\
           'sigma_w_HPF','rv_intercept',   'rv_slope']

# Distributions:

dists_linear_2p = ['uniform','uniform','uniform', \
         'uniform','uniform','uniform','uniform','uniform','uniform','uniform','uniform',\
         'uniform', 'uniform','uniform','fixed','uniform']

# Hyperparameters
hyperps_linear_2p =  [[0,1000],[2458473.75213848,2459025.63776411],[0,1000],[2458473.75213848,2459025.63776411],\
           [-10,10], [-10,10],[0,10], [0,1], [0,360], \
           [0,10], [0,1], [0,360], [0, 10], [0, 10],0,[0, 0.01]]


# Populate the priors dictionary:
for param, dist, hyperp in zip(params_linear_2p, dists_linear_2p, hyperps_linear_2p):
    priors_linear_2p[param] = {}
    priors_linear_2p[param]['distribution'], priors_linear_2p[param]['hyperparameters'] = dist, hyperp
    
dataset_linear_2p = juliet.load(priors = priors_linear_2p,  rvfilename=directory+'data.txt', out_folder = directory+'rvs_lineartrend_2planet')
results_linear_2p = dataset_linear_2p.fit(n_live_points = 300)`
[data.txt](https://github.com/nespinoza/juliet/files/6671322/data.txt)

Thanks for the quick answer!

**Comment by nespinoza** [comment]
I checked, and it seems this is a nested sampling issue, not a `juliet` one. Closing.
