### ISSUE TITLE
Tying parameters together in fitting

### ISSUE THREAD

**Issue by ThomasGWilson** [nespinoza/juliet#62]
Hi Nestor,

Myself and @sergiohoyer have been thinking about using Juliet to fit and detrend CHEOPS photometry (combined with data from other instruments). Like most space missions, data from different visits may exhibit subtly different systematics and so may need correcting independently.

One way to do this in Juliet would be to denote each visit as a different "instrument", hence allowing different basis vectors to be used in the detrending. However the issue then becomes ensuring the commonality of the limb-darkening coefficients. 

So we were wondering if there is any way to "tie" different parameters together in Juliet? For example, across different "instruments".

Cheers,

Tom

**Comment by nespinoza** [comment]
Hi @ThomasGWilson,

 Glad you are using `juliet` for this; the answer is yes! You can link them by setting the instrument names joined through underscores, e.g., `q1_CHEOPS1_CHEOPS2_CHEOPS3`, etc. 

 Let me know if this works for you.

 Happy fitting!
Néstor

**Comment by ThomasGWilson** [comment]
Hi Néstor,

That's fantastic! Thanks for the fast response!

Cheers,

Tom

**Comment by nespinoza** [comment]
Glad it was of help --- I'll make a note to document this :-).
