### ISSUE TITLE
UltraNest suuuper slow

### ISSUE THREAD

**Issue by JonasKemmer** [nespinoza/juliet#65]
Hey @nespinoza and @JohannesBuchner,
 
so far I was using `dynesty` for the sampling, however, I recently also started to play around with `UltraNest` because I like the MPI compatibility. However, compared to `dynesty` and `multinest`, it's suuuper slow and takes more than one hour for fits that are finished in less than 10 minutes by `dynesty` or `multinest`. Using the slice sampler, didn't help, as well as, setting OMP_NUM_THREADS=1 for MPI as suggested in the `UltraNest` documentation didn't fix the issue.

Do you have an idea what it could be? 

Best,
Jonas

**Comment by JohannesBuchner** [comment]
I take it that you mean "slow" to refer to the number of likelihood evaluations (algorithmic speed), not time spent in the UltraNest code? 

UltraNest will not compete with the MultiNest algorithm's speed. Its implementation is more careful, less ad-hoc and less aggressive than the MultiNest algorithm, which can yield biased results (see Beaujean&Caldwell2012, Nelson+2021 for example). The goal of UltraNest is to provide a robust and reliable method that gives the correct result in one run without the need to run several times or tune parameters.

I also take it that the slowness is unrelated to MPI (all algorithms were run the same way). If you have a MPI problem, that's usually related to missing mpi4py.

Please attach the debug.log file and/or the stdout.

You may want to try the frac_remain=0.5 and max_num_improvement_loops=0 run() parameters. https://johannesbuchner.github.io/UltraNest/ultranest.html#ultranest.integrator.ReactiveNestedSampler.run

**Comment by JonasKemmer** [comment]
Hey, 

thanks for the very quick answer! Actually, I see your point.  Using your suggested parameters, it now took about 45 minutes until the fit terminated and the debug.log states more than 3 million likelihood function evaluations. If I compare to dynamic dynesty (which also outputs the total number of likelihood calls), it's about 4 times more calls. However, the dynamic
 dynesty run finished in 5 minutes, so there seems to be also some discrepancy in the overhead. Multinest took in comparison ~8 minutes until it was finished.

**Comment by JohannesBuchner** [comment]
If it takes 4x more likelihood evaluations, but is 10x slower in wall clock time, that's strange. Maybe run with a profiler (`python -m cProfile -o prof.out myscript.py myarguments`, `snakeviz prof.out`). Also check which version you are using and try the latest.

**Comment by JonasKemmer** [comment]
Found the problem -- I am ashamed to admit this, but indeed, I was using an old version of ultranest. Now it works fine (a bit slower but on a reasonable timescale). Thanks a lot!

**Comment by nespinoza** [comment]
Thanks for figuring this one out folks!
