### ISSUE TITLE
Getting error when running the fitting command "dataset.fit()"

### ISSUE THREAD

**Issue by ghost** [nespinoza/juliet#67]
**Hello**

I'm sorry before if this problem isn't worth be noticed at all. I'm new to the code and tried to follow the code given in the [documentation](https://juliet.readthedocs.io/en/latest/user/quicktest.html). But when I tried to fit the example data with the `dataset.fit()` command, I encounter the following error:

`ValueError: not enough values to unpack (expected 2, got 1)`

It rises from this line:

`name, values = l.split('   ', 1)`

The fitting is actually done and the result is there in the file I specified. But when the code showed **analysing data from hats46/jomnest_.txt**, the above error appeared. It appears that I always encounter the error every time I run the `dataset.fit()` command. I really don't have any idea about it. Can somebody help me with this?

Thank you very much!

**Comment by nespinoza** [comment]
Hi @ghost,

 Thanks for using `juliet`! I presume you are following the [lightcurve fitting tutorial](https://juliet.readthedocs.io/en/latest/tutorials/transitfits.html) --- correct? I just tried running it in a freshly installed version of `juliet`, and the `dataset.fit()` seems to run just fine at least on my system. 

 Can you pass the _entire_ traceback you are getting? 

 Thanks!
Néstor
