### ISSUE TITLE
Problem loading my file from local path

### ISSUE THREAD

**Issue by GeoLek** [nespinoza/juliet#70]
Dear Nestor,

Congratulations for this package. This is the first time I use it and it seems to be a powerhouse. I want to incorporate Gaussian Processes into the code and played around with the sample notebook but also with data set downloaded via URL successfully. Now  I want to load files from my local path but I have a problem loading them with Juliet. I follow the instructions here: https://juliet.readthedocs.io/en/latest/user/priorsnparameters.html with "juliet.load" but with no successful outcome. 

Below I write some ways I tried to load my file following the documentation:

A)

import juliet
import numpy as np
import matplotlib.pyplot as plt

priors = {}
dataset = juliet.load(priors=priors, t_lc = times, y_lc = fluxes, yerr_lc = fluxes_error, lc_test.fits = /home/orion/Geo/lc_test.fits)
# Plot the data:
plt.errorbar(dataset, fmt='.')
plt.xlim([np.min(t),np.max(t)])
plt.xlabel('Time (BJD - 2457000)')
plt.ylabel('Relative flux')

Which gives a syntax error at "/home", so I put it in " ' ' " ('/home/orion/Geo/lc_test.fits') but it also gives an expression error. 

B)

Tried to simplify it: 
import juliet
import numpy as np
import matplotlib.pyplot as plt

dataset = juliet.load(lc_test = '/home/orion/Geo/lc_test.fits')

# Plot the data:
plt.errorbar(dataset, fmt='.')
plt.xlim([np.min(t),np.max(t)])
plt.xlabel('Time (BJD - 2457000)')
plt.ylabel('Relative flux')

But I get a unexpected argument error as well.

C)
import juliet
import numpy as np
import matplotlib.pyplot as plt

dataset = juliet.load('lc_test.fits == /home/orion/Geo/lc_test.fits')

# Plot the data:
plt.errorbar(dataset, fmt='.')
plt.xlim([np.min(t),np.max(t)])
plt.xlabel('Time (BJD - 2457000)')
plt.ylabel('Relative flux')

Error: No such file or directory but the directory is correct.

Can you please provide me with some solutions/directions? Thank you very much!!

**Comment by nespinoza** [comment]
Closing this as I think @icweaver had this covered with his answer (thanks Ian!).
