### ISSUE TITLE
Problem with dynamic dynesty

### ISSUE THREAD

**Issue by Jayshil** [nespinoza/juliet#71]
Hi Nestor,

There seems to be an issue with the `dynamic_dynesty` sampler in dataset.fit function, or maybe I am doing something wrong. Upon using `dynamic_dynesty` as a sampler, it shows the following error message.

`TypeError: DynamicNestedSampler() got an unexpected keyword argument 'nlive_init'`

In [this folder](https://github.com/Jayshil/hello-world/tree/master/dynamic_dynesty_bug) you will find a [notebook](https://github.com/Jayshil/hello-world/blob/master/dynamic_dynesty_bug/p1.ipynb) with an example code (along with data) to illustrate this issue.

Regards,
Jayshil

**Comment by Jayshil** [comment]
Hi @nespinoza,

So, this issue arises only when one uses the latest development version of `dynesty`, installed directly from the source code. However, I tried using it with the most stable version of `dynesty` from pip, and it is working now. So, the issue is solved for now, but maybe with new updates from `dynesty`, it will need to change `juliet` accordingly.

Hope this helps!

--Jayshil

**Comment by Jayshil** [comment]
Hi @nespinoza,

As it turns out, the issue is back again with the current latest stable version of `dynesty` (version 1.2.2). It was not appearing until `dynesty' v1.1. The quick solution to this would be to install v1.1 of `dynesty`, but it should be possible to make `juliet` compatible with the new release of `dynesty`.

--Jayshil

**Comment by nespinoza** [comment]
Hey @Jayshil ---sorry for the delay on this. This has been fixed in `dev` (https://github.com/nespinoza/juliet/commit/b6eeb26e897e3dea5c2f92d072ed809d7fc45b16). Was a simple change!

N.

**Comment by Jayshil** [comment]
Hi @nespinoza, thanks for this! We can close this issue now!
--Jayshil
