### ISSUE TITLE
Grazing transit issue

### ISSUE THREAD

**Issue by angelicaps** [nespinoza/juliet#83]
I am analyzing some new detections with Juliet and one of them is in grazing transit. As a result the depth and impact parameter are correlated and they look kind of bimodal . I tried to use the mode instead of median or mean for the calculation but it doesn't really pick the peak because of the bin number. I tried to increase the bin number but from e.g 40 to 50 bins the results are very different. Using the mode I also have trouble getting uncertainties since the lower and max will be under or over estimated. Did you ever deal with something like that? In that case what is the best way to get uncertainties?

Thank you a lot!

**Comment by nespinoza** [comment]
Hi @angelicaps --- coming late to this issue, very sorry. Basic reason is that this isn't an issue with `juliet`, but a general question about handling priors. In my experience, using statistics that work well on unimodal distributions (mean, mode, median) on each individual mode works best. 

Closing this (as it's not an issue)!

N.
